apiVersion: v1
kind: Service
metadata:
  name: object-detector-service
spec:
  selector:
    app: object-detector-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1024
  type: NodePort